### ISSUE TITLE
[Feature Request] Change/Customize Controller Mappings

### ISSUE THREAD

**Issue by MarioAndWeegee3** [X16Community/x16-emulator#182]
I am running the emulator on Linux with a Nintendo Switch Pro controller and the mappings for the buttons are incorrect. It is impossible to play any game with the controller.

These are the button mappings:

|Switch|SNES|
|-|-|
|`B`|`R`|
|`A`|`not connected`|
|`Y`|`A`|
|`X`|`B`|
|`-`|`Y`|
|`+`|`Select`|
|`d-pad up`|`Start`|
|`d-pad left`|`d-pad down`|
|`d-pad right`|`d-pad left`|
|`d-pad down`|`d-pad up`|
|`L`|`X`|
|`R`|`L`|

Here's the SDL mapping string, if it helps:
```
030056fb7e0500000920000000026803,Nintendo Switch Pro Controller,a:b1,b:b0,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b3,y:b2,platform:Linux,
```

**Comment by catmeow72** [comment]
I've diagnosed the problem and am preparing to create a pull request. Turns out there was an off by one error, as well as an incorrect bitmask that blocked the highest controller bit from working.

**Comment by mooinglemur** [comment]
This was inadvertently caused by a change in the ROM.  While the ROM update worked on hardware, a subtle change messed with the emulated joystick mapping.  Please try again with a recently-built ROM from the GitHub actions page, such as this one https://github.com/X16Community/x16-rom/actions/runs/6701369244
