### ISSUE TITLE
SYS A000 caused unexpected results.

### ISSUE THREAD

**Issue by zpc0070** [X16Community/x16-emulator#206]
SYS $A000 does NOT act like SYS A000.  I don't know if this is an issue with the emulator or the system ROM.
SYS $A000 acts as expected, but SYS A000 does NOT give an error and will run.  BUT... the program can NOT WRITE to memory!!

**Comment by lgblgblgb** [comment]
> SYS $A000 does NOT act like SYS A000. I don't know if this is an issue with the emulator or the system ROM. SYS $A000 acts as expected, but SYS A000 does NOT give an error and will run. BUT... the program can NOT WRITE to memory!!

I'm not sure if I understand correctly, but using `SYS A000` (without the `$`) will probably do `SYS 0` (and thus it probably crashes or something, since there is no valid code to execute at memory address zero). This is because `A000` alone (without the `$`) means a variable named `A000`, which is probably zero in value (unless if you set it to other value before). So of course `SYS A000` does not give error, since it's legitimate BASIC, meaning you want to `SYS` to address given by the value of the variable named as `A000`. To see the difference, try these BASIC commands:

```
PRINT $A000
PRINT A000
A000 = 2023
PRINT A000
PRINT $A000
```

**Comment by zpc0070** [comment]
> > SYS $A000 does NOT act like SYS A000. I don't know if this is an issue with the emulator or the system ROM. SYS $A000 acts as expected, but SYS A000 does NOT give an error and will run. BUT... the program can NOT WRITE to memory!!
> 
> I'm not sure if I understand the reported problem correctly, but using `SYS A000` (without the `$`) will probably do `SYS 0` (and thus it probably crashes or something, since there is no valid code to execute at memory address zero). This is because `A000` alone (without the `$`) means a variable named `A000`, which is probably zero in value (unless if you set it to other value before). So of course `SYS A000` does not give error, since it's legitimate BASIC, meaning you want to `SYS` to address given by the value of the variable named as `A000`. To see the difference, try these BASIC commands:
> 
> ```
> PRINT $A000
> PRINT A000
> A000 = 2023
> PRINT A000
> PRINT $A000
> ```

It DOES run.  It doesn't do a SYS 0.  It does a SYS $A000 but won't allow memory save.  Acts as if all memory save are to ROM.
