### ISSUE TITLE
Try to build Linux releases in the future with an older toolchain and glibc to broaden distro compatibility

### ISSUE THREAD

**Issue by mooinglemur** [X16Community/x16-emulator#34]
https://cx16forum.com/forum/viewtopic.php?p=26135#p26135

**Comment by irmen** [comment]
This should be as easy as replacing `ubuntu-latest` by `ubuntu-20.04` or maybe even `ubuntu-18.04` in the actions yaml?  Although the latter is deprecated    https://github.com/actions/runner-images

**Comment by irmen** [comment]
so 20.04 is how low we can go ?  That seems to be around 3 years old.

**Comment by mooinglemur** [comment]
Yeah, it seems like GitHub is taking those 5 year Ubuntu LTS cycles seriously.  Probably also a decision for allocation of resources, trying to minimize the number of runner images they have to maintain.

**Comment by mooinglemur** [comment]
Let's try to get an ARM build working for RPi too.

**Comment by mobluse** [comment]
I have a Raspberry Pi 4 Model B with most updated Debian GNU/Linux 11 (bullseye) aarch64 (i.e. the standard OS for this system). I think you should provide a binary also for this since it is a common computer even if it is difficult to buy right now. Normally I have compiled the emulator and ROM myself, but it would be easier if it was available as a binary. It doesn't have to be statically linked, but it should be runnable if you install the required packages from the distribution using apt. Maybe the emulator for ARM64 could be included in the Linux package so that you don't need two Linux packages. Using R41 the emulator often runs at 100% with my CPU (Cortex-A72 (4) @ 1.800GHz) even when generating sound. I hope R42 also can run at 100%.

**Comment by mooinglemur** [comment]
I spent some time today trying to set up cross compiling for aarch64 under the GitHub Actions build environment.  It's not trivial.  It's definitely on the list but it's not as simple as cross-compiling the emulator by itself using the aarch64 cross compiler.  The build environment needs to have the arm64 versions of zlib, sdl2, and all of its dependencies at build time.

**Comment by irmen** [comment]
You can sudo apt-get install stuff in the actions script run step

**Comment by mobluse** [comment]
Are you aware of that one can install R41 in Linux using snap for many architectures?

https://snapcraft.io/x16emu  

https://github.com/popey/x16emu-snap/

Maybe snap could also be used for R42.

**Comment by irmen** [comment]
Looks like @popey needs to change their build config for those snaps, to point to this repository instead , as the "official" one has become stale

**Comment by mooinglemur** [comment]
@mobluse can you please test the aarch64 artifact at https://github.com/mooinglemur/x16-emulator/actions/runs/4370275792 at your convenience?

**Comment by mooinglemur** [comment]
Or if you instead have a 32-bit environment, I also was able to add an armhf target here https://github.com/mooinglemur/x16-emulator/actions/runs/4370549993

**Comment by mooinglemur** [comment]
ARM releases posted in the release section, as at least the 32 bit armhf build was tested and confirmed working.

If there are any issues with those builds, or any other problems with the emu, please open a new issue.

**Comment by irmen** [comment]
I guess we have to mention the availability of the alternate platform builds in the linux quickstart guide

**Comment by mobluse** [comment]
> @mobluse can you please test the aarch64 artifact at https://github.com/mooinglemur/x16-emulator/actions/runs/4370275792 at your convenience?

Yes, all my programs in the forum for R41 work with R42 aarch64 in Debian Bullseye on Raspberry Pi 4 B, but I had to modify one that used hard coded addresses in ROM.
