### ISSUE TITLE
Audio is claimed not to playback as consistently in r42 as from r41 or other previous versions

### ISSUE THREAD

**Issue by indigodarkwolf** [X16Community/x16-emulator#37]
The 8-Bit Guy on Discord:
> Is it just me... or does the sound not work as well in the latest version of the emulator?
> It seems the vera is too loud. And when the music first starts, the emulator kind of chokes on sound.

@SlithyMatt on Discord:
> the sound has definitely not worked as well on Linux with the last few releases
> I get all sorts of pops and things from about R40 on

Ender on Discord:
> I'm running on windows, and I had left Lemur's BASIC sound demo playing for a while and it will eventually start to choke on the sound. Nothing short of closing and opening the emulator seems to fix it.  The window title doesn't show less than 100% emulation speed, so I'm not sure what's making it skip
> I've noticed it while playing Tetrads in the past too

@tomxp411 on Discord:
> Honestly, I'm getting a lot of pops and dropouts in FM synthesis. I got them before, too, but it's definitely not "great".

**Comment by mooinglemur** [comment]
Oddly, R42 has been the best-performing release for me when it comes to emulator audio.  I used to get several clicks and pops per second.  Linux in particular was pretty bad in R41.

**Comment by mobluse** [comment]
I have the opposite experience PSG sound is better in R41 than R42, but this might be due to that R42 is slower i.e. the emulation on a slow system such as x86-32 Celeron 900 MHz (EeePC 900) has a lower percentage of full speed than R39 (I don't have R41 on my EeePC).

**Comment by irmen** [comment]
Here are my findings about this.

I am on Linux and made 2 changes that for me, resolved almost all of the audio crackles: 
* double the audio buffer size in `src/audio.c` from 256 to 512  (and adjust `SAMP_POS_FRAC_BITS` accordingly from `24` to `23`)  (note: doubling it again to 1024 breaks stuff severely somehow)
* run the emulator with environment variable `PULSE_LATENCY_MSEC=20` set.   My system uses Pulse audio.

I don't know what the equivalent of the #2 would be on windows

Another thing that I experimented with was telling the emulator to not use pulseaudio but revert to Alsa using `SDL_AUDIODRIVER=alsa` ,   and that improved matters as well.  It looks like there may be some SDL <-> pulseaudio buffering shenanigans going on.

No idea how this all relates to the Windows version, because Pulseaudio obviously is not a thing there.

**Comment by mooinglemur** [comment]
>  Is it just me... or does the sound not work as well in the latest version of the emulator?
>  It seems the vera is too loud. And when the music first starts, the emulator kind of chokes on sound.

This should be helped by #61

**Comment by mooinglemur** [comment]
#88 is also a marked improvement, IMO.

**Comment by irmen** [comment]
Oh, this is nice!
My 'karaoke' music streaming demo now works equally well on hostfs as on sdcard image.   Great work
